# Generated by make process
# CHANGELOG.md
# LICENSE
# README.md
# conf/cmtupd.xml
# configure.bat
# res/scripts/EnvReset.bat
# res/scripts/VsCmd.bat
# res/scripts/vs15.bat
# res/scripts/vs16.bat
# res/scripts/vs17.bat
# res/scripts/vs17pre.bat
# res/scripts/vs18pre.bat
